#################################################
### Base image with Python 3.12 + uv           ##
#################################################
FROM ghcr.io/rtae/myochallenge/myochallenge-base:latest

WORKDIR /app

COPY train.py ./
COPY env_factory.py ./
COPY worker_env.py ./
COPY manager_env.py ./
COPY lattice ./lattice

COPY config.py ./
COPY utils.py ./

COPY callbacks ./callbacks

CMD ["python", "train.py"]