#################################################
### Base image with Python 3.12 + uv           ##
#################################################
FROM ghcr.io/rtae/myochallenge/myochallenge-base:latest

WORKDIR /app

COPY train.py ./
COPY env_factory.py ./
COPY config.py ./
COPY hrl_utils.py ./
COPY manager_env.py ./
COPY worker_env.py ./

COPY callbacks ./callbacks


CMD ["python", "train.py"]